name: dicom_autopsy_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit=1.20.0
  - pydicom=2.3.0
  - numpy=1.23.5
  - scipy=1.9.3
  - pandas=1.5.3
  - pillow=9.4.0
  - opencv=4.7.0
  - scikit-image=0.19.3
  - matplotlib=3.6.2
  - plotly=5.13.1
  - black=22.3.0            # Formatação automática de código
  - flake8=5.0.4            # Linter para qualidade do código
  - ipython=8.10.0          # Console interativo para testes rápidos
  - pytest=7.2.0            # Testes automatizados
  - pip
  - pip:
    - reportlab==3.6.12
    - rich                   # Saída de logs e erros mais legível
    - memory-profiler        # Para análise de uso de memória (opcional)
    - python-dotenv          # Para gerenciar variáveis de ambiente (opcional)
